// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: mag_slide_switch

#include "../ui.h"

lv_obj_t * ui_MagSlideSwitchScreen = NULL;
lv_obj_t * ui_IphoneImage = NULL;
lv_obj_t * ui_EchoEarBaseImage = NULL;
lv_obj_t * ui_BellImage = NULL;
lv_obj_t * ui_EventLabel = NULL;
lv_obj_t * ui_FishImage = NULL;
lv_obj_t * ui_PairingImage = NULL;
lv_obj_t * ui_accessoryImage = NULL;
lv_obj_t * ui_IphoneImage2 = NULL;
// event funtions

// build funtions

void ui_MagSlideSwitchScreen_screen_init(void)
{
    ui_MagSlideSwitchScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MagSlideSwitchScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MagSlideSwitchScreen, lv_color_hex(0xD5E3E3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MagSlideSwitchScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IphoneImage = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_IphoneImage, &ui_img_iphone_flat_png);
    lv_obj_set_width(ui_IphoneImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IphoneImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IphoneImage, 0);
    lv_obj_set_y(ui_IphoneImage, 230);
    lv_obj_set_align(ui_IphoneImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IphoneImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_IphoneImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_IphoneImage, 200);

    ui_EchoEarBaseImage = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_EchoEarBaseImage, &ui_img_echoear_1_png);
    lv_obj_set_width(ui_EchoEarBaseImage, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_EchoEarBaseImage, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_x(ui_EchoEarBaseImage, -115);
    lv_obj_set_y(ui_EchoEarBaseImage, -24);
    lv_obj_set_align(ui_EchoEarBaseImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_EchoEarBaseImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_EchoEarBaseImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_EchoEarBaseImage, 320);

    ui_BellImage = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_BellImage, &ui_img_bell_2_png);
    lv_obj_set_width(ui_BellImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BellImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BellImage, -39);
    lv_obj_set_y(ui_BellImage, 79);
    lv_obj_set_align(ui_BellImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BellImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BellImage, 220);

    ui_EventLabel = lv_label_create(ui_MagSlideSwitchScreen);
    lv_obj_set_width(ui_EventLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EventLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EventLabel, 90);
    lv_obj_set_y(ui_EventLabel, -55);
    lv_obj_set_align(ui_EventLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EventLabel, "SLIDE DOWN!");
    lv_obj_set_style_text_color(ui_EventLabel, lv_color_hex(0x5C73A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_EventLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_EventLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EventLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FishImage = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_FishImage, &ui_img_fish_png);
    lv_obj_set_width(ui_FishImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FishImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FishImage, -30);
    lv_obj_set_y(ui_FishImage, 46);
    lv_obj_set_align(ui_FishImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FishImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_FishImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_FishImage, 255);

    ui_PairingImage = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_PairingImage, &ui_img_pairing_png);
    lv_obj_set_width(ui_PairingImage, 48);
    lv_obj_set_height(ui_PairingImage, 48);
    lv_obj_set_x(ui_PairingImage, -2);
    lv_obj_set_y(ui_PairingImage, -104);
    lv_obj_set_align(ui_PairingImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PairingImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_PairingImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_accessoryImage = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_accessoryImage, &ui_img_ice_cream_png);
    lv_obj_set_width(ui_accessoryImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_accessoryImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_accessoryImage, -44);
    lv_obj_set_y(ui_accessoryImage, 55);
    lv_obj_set_align(ui_accessoryImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_accessoryImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_accessoryImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_accessoryImage, -80);

    ui_IphoneImage2 = lv_image_create(ui_MagSlideSwitchScreen);
    lv_image_set_src(ui_IphoneImage2, &ui_img_iphone_upright_png);
    lv_obj_set_width(ui_IphoneImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IphoneImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IphoneImage2, 254);
    lv_obj_set_y(ui_IphoneImage2, 219);
    lv_obj_set_align(ui_IphoneImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_IphoneImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_IphoneImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_IphoneImage2, 160);

}

void ui_MagSlideSwitchScreen_screen_destroy(void)
{
    if(ui_MagSlideSwitchScreen) lv_obj_del(ui_MagSlideSwitchScreen);

    // NULL screen variables
    ui_MagSlideSwitchScreen = NULL;
    ui_IphoneImage = NULL;
    ui_EchoEarBaseImage = NULL;
    ui_BellImage = NULL;
    ui_EventLabel = NULL;
    ui_FishImage = NULL;
    ui_PairingImage = NULL;
    ui_accessoryImage = NULL;
    ui_IphoneImage2 = NULL;

}
