// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: mag_slide_switch

#ifndef UI_MAGSLIDESWITCHSCREEN_H
#define UI_MAGSLIDESWITCHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MagSlideSwitchScreen
extern void ui_MagSlideSwitchScreen_screen_init(void);
extern void ui_MagSlideSwitchScreen_screen_destroy(void);
extern lv_obj_t * ui_MagSlideSwitchScreen;
extern lv_obj_t * ui_IphoneImage;
extern lv_obj_t * ui_EchoEarBaseImage;
extern lv_obj_t * ui_BellImage;
extern lv_obj_t * ui_EventLabel;
extern lv_obj_t * ui_FishImage;
extern lv_obj_t * ui_PairingImage;
extern lv_obj_t * ui_accessoryImage;
extern lv_obj_t * ui_IphoneImage2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

