// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: mag_slide_switch

#ifndef _MAG_SLIDE_SWITCH_UI_H
#define _MAG_SLIDE_SWITCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MagSlideSwitchScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * SingleClick_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * SlideUp_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * SlideDown_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * RemoveFromUp_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * RemoveFromDown_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PlaceFromUp_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PlaceFromDown_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * FishAttached_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * FishDetached_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PairingCancelledLeft_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PairingCancelledRight_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PairingIcon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * PairingCancelledIcon_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * accessoryAttached_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * accessoryDetached_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * IphoneFlatAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * IphoneDetectFromDownAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * IphoneRemoveFromDownAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * IphoneFlatRemoveAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * iphoneapproachfrontanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * Baseiphoneapproachfrontanim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * iphoneRemoveFromFrontAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * BaseiphoneRemoveFromFrontAnim_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_iphone_flat_png);    // assets/iphone_flat.png
LV_IMG_DECLARE(ui_img_echoear_1_png);    // assets/echoear_1.png
LV_IMG_DECLARE(ui_img_bell_2_png);    // assets/bell_2.png
LV_IMG_DECLARE(ui_img_fish_png);    // assets/fish.png
LV_IMG_DECLARE(ui_img_pairing_png);    // assets/Pairing.png
LV_IMG_DECLARE(ui_img_donut_png);    // assets/donut.png
LV_IMG_DECLARE(ui_img_ice_cream_png);    // assets/ice_cream.png
LV_IMG_DECLARE(ui_img_iphone_upright_png);    // assets/iphone_upright.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
