// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: mag_slide_switch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void app_ui_event_mag_slide_up(lv_event_t * e);
void app_ui_event_mag_slide_down(lv_event_t * e);
void app_ui_event_mag_remove_from_up(lv_event_t * e);
void app_ui_event_mag_place_from_up(lv_event_t * e);
void app_ui_event_mag_remove_from_down(lv_event_t * e);
void app_ui_event_mag_place_from_down(lv_event_t * e);
void app_ui_event_mag_single_click(lv_event_t * e);
void app_ui_event_mag_fish_attached(lv_event_t * e);
void app_ui_event_mag_fish_detached(lv_event_t * e);
void app_ui_event_mag_pairing(lv_event_t * e);
void app_ui_event_mag_pairing_cancelled(lv_event_t * e);
void app_ui_event_mag_ice_cream_attached(lv_event_t * e);
void app_ui_event_mag_ice_cream_detached(lv_event_t * e);
void app_ui_event_mag_donut_attached(lv_event_t * e);
void app_ui_event_mag_donut_detached(lv_event_t * e);
void app_ui_event_mag_iphone_lean_front(lv_event_t * e);
void app_ui_event_mag_iphone_lean_front_detached(lv_event_t * e);
void app_ui_event_mag_iphone_under_base(lv_event_t * e);
void app_ui_event_mag_iphone_under_base_detached(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
