// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: mag_slide_switch

#include "ui.h"
#include "esp_log.h"

static const char *TAG = "ui_events";

/* ========== Event Label Display Configuration ========== */
#define EVENT_LABEL_DISPLAY_TIME_MS     (800)      /**< Event label display duration (ms) */
#define EVENT_LABEL_FADE_TIME_MS        (200)       /**< Event label fade out animation duration (ms) */

/**
 * @brief 设置对象透明度的动画回调函数
 * 
 * @param obj LVGL 对象指针
 * @param opa 透明度值 (0-255)
 * 
 * @note 这是一个包装函数，用于在动画中设置对象透明度
 */
static void anim_set_opa_cb(void * obj, int32_t opa)
{
    lv_obj_set_style_opa((lv_obj_t *)obj, (lv_opa_t)opa, 0);
}

/**
 * @brief 显示事件标签并自动隐藏
 * 
 * @param text 要显示的文本内容
 * 
 * @note 此函数会：
 *       1. 立即显示标签（透明度 255）
 *       2. 更新标签文本
 *       3. 延迟 EVENT_LABEL_DISPLAY_TIME_MS 后开始淡出动画
 *       4. 淡出动画持续 EVENT_LABEL_FADE_TIME_MS
 */
static void show_event_label_with_auto_hide(const char *text)
{
    if (ui_EventLabel == NULL) {
        ESP_LOGW(TAG, "ui_EventLabel is NULL");
        return;
    }
    
    // 立即显示标签（设置透明度为 255，完全不透明）
    lv_obj_set_style_opa(ui_EventLabel, LV_OPA_COVER, 0);
    
    // 更新文本内容
    lv_label_set_text(ui_EventLabel, text);
    
    // 创建淡出动画
    lv_anim_t anim_fade;
    lv_anim_init(&anim_fade);
    lv_anim_set_var(&anim_fade, ui_EventLabel);
    lv_anim_set_exec_cb(&anim_fade, anim_set_opa_cb);  // 使用包装函数
    lv_anim_set_values(&anim_fade, LV_OPA_COVER, LV_OPA_TRANSP);  // 从完全不透明到完全透明
    lv_anim_set_time(&anim_fade, EVENT_LABEL_FADE_TIME_MS);
    lv_anim_set_delay(&anim_fade, EVENT_LABEL_DISPLAY_TIME_MS);  // 延迟后开始淡出
    lv_anim_set_path_cb(&anim_fade, lv_anim_path_ease_in_out);
    lv_anim_start(&anim_fade);
}

/**
 * @brief 磁吸滑动开关向上滑动事件处理
 * 铃铛图片从右下角平滑移动到左上角
 * 起始位置: (37, 57)
 * 目标位置: (26, 19)
 * 动画时长: 200ms
 */
void app_ui_event_mag_slide_up(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }

    show_event_label_with_auto_hide("SLIDE UP!");
    
    // 确保图片可见（移除隐藏标志并设置透明度）
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_opa(ui_BellImage, LV_OPA_COVER, 0);

    SlideUp_Animation(ui_BellImage, 0);
}

/**
 * @brief 磁吸滑动开关向下滑动事件处理
 * 铃铛图片从左上角平滑移动到右下角
 * 起始位置: (26, 19)
 * 目标位置: (37, 57)
 * 动画时长: 200ms
 */
void app_ui_event_mag_slide_down(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }

    show_event_label_with_auto_hide("SLIDE DOWN!");
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_opa(ui_BellImage, LV_OPA_COVER, 0);
    
    SlideDown_Animation(ui_BellImage, 0);
}

/**
 * @brief 从上面拿下磁吸滑块事件处理
 * 铃铛图片从左上角平滑移动到右上角外
 * 起始位置: (26, 19)
 * 目标位置: (147, -32)
 * 动画时长: 200ms
 */
void app_ui_event_mag_remove_from_up(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("REMOVE\nFROM UP!");
    
    // 确保图片可见（移除隐藏标志并设置透明度）
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);
    
    RemoveFromUp_Animation(ui_BellImage, 0);
}

/**
 * @brief 从上面吸附磁吸滑块事件处理
 * 铃铛图片从右上角外平滑移动到左上角
 * 起始位置: (147, -32)
 * 目标位置: (26, 19)
 * 动画时长: 200ms
 */
void app_ui_event_mag_place_from_up(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("PLACE\nFROM UP!");
    
    // 确保图片可见（移除隐藏标志并设置透明度）
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_opa(ui_BellImage, LV_OPA_COVER, 0);
    
    // 设置起始位置
    PlaceFromUp_Animation(ui_BellImage, 0);
}

/**
 * @brief 从下面拿下磁吸滑块事件处理
 * 铃铛图片从右下角平滑移动到右侧外
 * 起始位置: (37, 57)
 * 目标位置: (155, 54)
 * 动画时长: 200ms
 */
void app_ui_event_mag_remove_from_down(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }

    show_event_label_with_auto_hide("REMOVE\nFROM DOWN!");
    
    // 确保图片可见（移除隐藏标志并设置透明度）
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);

    RemoveFromDown_Animation(ui_BellImage, 0);
}

/**
 * @brief 从下面吸附磁吸滑块事件处理
 * 铃铛图片从右侧外平滑移动到右下角
 * 起始位置: (155, 54)
 * 目标位置: (37, 57)
 * 动画时长: 200ms
 */
void app_ui_event_mag_place_from_down(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("PLACE\nFROM DOWN!");
    
    // 确保图片可见（移除隐藏标志并设置透明度）
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_opa(ui_BellImage, LV_OPA_COVER, 0);
    
    // 设置起始位置
    PlaceFromDown_Animation(ui_BellImage, 0);
}

/**
 * @brief 单击事件处理
 * 铃铛图片从初始位置移动并旋转,然后恢复
 * 起始位置: (-13, 66), 角度: 0
 * 中间位置: (0, 95), 角度: 向右旋转45度
 * 结束位置: (-13, 66), 角度: 0
 * 动画时长: 300ms (往返各150ms)
 */
void app_ui_event_mag_single_click(lv_event_t * e)
{
    // 确保对象存在
    if (ui_BellImage == NULL) {
        ESP_LOGW(TAG, "ui_BellImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("SINGLE CLICK!");
    
    // 确保图片可见（移除隐藏标志并设置透明度）
    lv_obj_remove_flag(ui_BellImage, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_opa(ui_BellImage, LV_OPA_COVER, 0);
    
    SingleClick_Animation(ui_BellImage, 0);
}

void app_ui_event_mag_fish_attached(lv_event_t * e)
{
    // 确保对象存在
    if (ui_FishImage == NULL) {
        ESP_LOGW(TAG, "ui_FishImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("FISH\nATTACHED!");
    
    FishAttached_Animation(ui_FishImage, 0);
}

void app_ui_event_mag_fish_detached(lv_event_t * e)
{
    // 确保对象存在
    if (ui_FishImage == NULL) {
        ESP_LOGW(TAG, "ui_FishImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("FISH\nDETACHED!");

    FishDetached_Animation(ui_FishImage, 0);
}

void app_ui_event_mag_pairing(lv_event_t * e)
{
    // 确保对象存在
    if (ui_FishImage == NULL) {
        ESP_LOGW(TAG, "ui_FishImage is NULL, cannot update position");
        return;
    }

    PairingCancelledLeft_Animation(ui_EchoEarBaseImage, 0);
    lv_obj_set_style_opa(ui_PairingImage, LV_OPA_COVER, 0);
    PairingIcon_Animation(ui_PairingImage, 500);
}

void app_ui_event_mag_pairing_cancelled(lv_event_t * e)
{
    // 确保对象存在
    if (ui_FishImage == NULL) {
        ESP_LOGW(TAG, "ui_FishImage is NULL, cannot update position");
        return;
    }
    
    PairingCancelledIcon_Animation(ui_PairingImage, 0);
    PairingCancelledRight_Animation(ui_EchoEarBaseImage, 500);
}

/**
 * @brief 雪糕附着事件处理
 * 显示雪糕图片
 */
void app_ui_event_mag_ice_cream_attached(lv_event_t * e)
{
    // 确保对象存在
    if (ui_accessoryImage == NULL) {
        ESP_LOGW(TAG, "ui_accessoryImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("ICE CREAM\nATTACHED!");

    lv_image_set_src(ui_accessoryImage, &ui_img_ice_cream_png);
    accessoryAttached_Animation(ui_accessoryImage, 0);
}

/**
 * @brief 雪糕分离事件处理
 * 隐藏雪糕图片
 */
void app_ui_event_mag_ice_cream_detached(lv_event_t * e)
{
    // 确保对象存在
    if (ui_accessoryImage == NULL) {
        ESP_LOGW(TAG, "ui_accessoryImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("ICE CREAM\nDETACHED!");
    
    lv_image_set_src(ui_accessoryImage, &ui_img_ice_cream_png);
    accessoryDetached_Animation(ui_accessoryImage, 0);
}

/**
 * @brief 甜甜圈附着事件处理
 * 显示甜甜圈图片
 */
void app_ui_event_mag_donut_attached(lv_event_t * e)
{
    // 确保对象存在
    if (ui_accessoryImage == NULL) {
        ESP_LOGW(TAG, "ui_accessoryImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("DONUT\nATTACHED!");
    
    lv_image_set_src(ui_accessoryImage, &ui_img_donut_png);
    accessoryAttached_Animation(ui_accessoryImage, 0);
}

/**
 * @brief 甜甜圈分离事件处理
 * 隐藏甜甜圈图片
 */
void app_ui_event_mag_donut_detached(lv_event_t * e)
{
    // 确保对象存在
    if (ui_accessoryImage == NULL) {
        ESP_LOGW(TAG, "ui_accessoryImage is NULL, cannot update position");
        return;
    }
    
    show_event_label_with_auto_hide("DONUT\nDETACHED!");
    
    lv_image_set_src(ui_accessoryImage, &ui_img_donut_png);
    accessoryDetached_Animation(ui_accessoryImage, 0);
}

/**
 * @brief iPhone 正面倚靠事件处理
 * 显示事件标签
 */
void app_ui_event_mag_iphone_lean_front(lv_event_t * e)
{
    ESP_LOGI(TAG, "[EVENT] iphone_lean_front triggered, ui_IphoneImage2=%p, ui_EchoEarBaseImage=%p",
             (void*)ui_IphoneImage2, (void*)ui_EchoEarBaseImage);
    if (ui_IphoneImage2 == NULL || ui_EchoEarBaseImage == NULL) {
        ESP_LOGW(TAG, "iphone_lean_front: NULL object, skip animation");
        return;
    }
    show_event_label_with_auto_hide("iPhone\nLEAN FRONT!");
    iphoneapproachfrontanim_Animation(ui_IphoneImage2, 0);
    Baseiphoneapproachfrontanim_Animation(ui_EchoEarBaseImage, 0);
}

/**
 * @brief iPhone 从正面离开事件处理
 * 显示事件标签
 */
void app_ui_event_mag_iphone_lean_front_detached(lv_event_t * e)
{
    ESP_LOGI(TAG, "[EVENT] iphone_lean_front_detached triggered, ui_IphoneImage2=%p, ui_EchoEarBaseImage=%p",
             (void*)ui_IphoneImage2, (void*)ui_EchoEarBaseImage);
    if (ui_IphoneImage2 == NULL || ui_EchoEarBaseImage == NULL) {
        ESP_LOGW(TAG, "iphone_lean_front_detached: NULL object, skip animation");
        return;
    }
    show_event_label_with_auto_hide("iPhone\nFRONT DETACHED!");
    iphoneRemoveFromFrontAnim_Animation(ui_IphoneImage2, 0);
    BaseiphoneRemoveFromFrontAnim_Animation(ui_EchoEarBaseImage, 0);
}

/**
 * @brief iPhone 在底座下事件处理
 * 显示事件标签
 */
void app_ui_event_mag_iphone_under_base(lv_event_t * e)
{
    ESP_LOGI(TAG, "[EVENT] iphone_under_base triggered, ui_IphoneImage=%p, ui_EchoEarBaseImage=%p",
             (void*)ui_IphoneImage, (void*)ui_EchoEarBaseImage);
    if (ui_IphoneImage == NULL || ui_EchoEarBaseImage == NULL) {
        ESP_LOGW(TAG, "iphone_under_base: NULL object, skip animation");
        return;
    }
    show_event_label_with_auto_hide("iPhone\nUNDER BASE!");
    IphoneFlatAnim_Animation(ui_IphoneImage, 0);
    IphoneDetectFromDownAnim_Animation(ui_EchoEarBaseImage, 0);
}

/**
 * @brief iPhone 从底座下离开事件处理
 * 显示事件标签
 */
void app_ui_event_mag_iphone_under_base_detached(lv_event_t * e)
{
    ESP_LOGI(TAG, "[EVENT] iphone_under_base_detached triggered, ui_IphoneImage=%p, ui_EchoEarBaseImage=%p",
             (void*)ui_IphoneImage, (void*)ui_EchoEarBaseImage);
    if (ui_IphoneImage == NULL || ui_EchoEarBaseImage == NULL) {
        ESP_LOGW(TAG, "iphone_under_base_detached: NULL object, skip animation");
        return;
    }
    show_event_label_with_auto_hide("iPhone\nBASE DETACHED!");
    IphoneFlatRemoveAnim_Animation(ui_IphoneImage, 0);
    IphoneRemoveFromDownAnim_Animation(ui_EchoEarBaseImage, 0);
}
